# These are supported funding model platforms

github: [jamesburchill]
custom: ["https://www.paypal.me/jamesburchill", jcb.dev]
custom: ["https://www.buymeacoffee.com/jamesburchill", BuyMeACoffee.com]
